# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyperTrackSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'HyperTrack'
  pod 'GzipSwift', :git => 'https://github.com/1024jp/GzipSwift.git', :branch => 'swift4'

  # Pods for HyperTrackSample

end
